### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/bayesian-pipelines-pixels#1]
Useful links: 
- [Project Proposal](https://docs.google.com/document/d/1WjaWRYXzagTe7xKvUXUc58yc6hdNVZaxdt64bkXsfDo/edit)

# Generative Model

## Stage 0: Setting things up
- single image per band
- use galsim for now 
- [ ] #7
- [ ] #37
- [ ] #26
- [ ] #21
- [ ] #25 
- [ ] #22 
- [x] #23 
- [x] #24 
- [x] #6
- [x] #2
- [x] #3
- [x] #4
- [x] #9
- [x] #5
- [x] #8
- [x] #10

## Stage 1: Multiband / redshifts/ variable shear
- single image per band
- [ ] multiband 
- [ ] redshift + SEDs
- [ ] variable shear
- [ ] galaxy locations poisson process of 2D density field
- [ ] feed angular power spectrum to galsim/[colore](https://arxiv.org/abs/2111.05069) -> 2D gaussian density map
- [ ] bin galaxies by true redshift
- [ ] lensing magnifications

## Stage2: Blending / Impact of PSF
- [ ] blending effects
- [ ] noisy PSF estimate
- [ ] use correlation functions in PSF 

# Inference

## Stage 0
**Goals:** 
- connect BLISS with JIF/BFD and recover constant shear 
- start defining what what outputs look like: probabilistic magnitudes + shear

**Tasks:**
- [ ] #11
- [ ] #12
- [ ] #13
- [ ] #14
- [ ] #15

## Stage 1
- BFD is already multi-band (can potentially photo-z)
- [ ] check that we recover power spectrum (?) 
- [ ] assume we know true redshift
- [ ] connect with RAIL (?)
    - catalogs: some aspect of photometry + position
    - how to connect posterior samples of photometry 
    - [tables_io](https://github.com/LSSTDESC/tables_io)

## Stage 2 
- [ ] recovering binning (tomo challenge)
- [ ] run on DC2

**Comment by EiffL** [comment]
So, here I propose a slight modification of our baseline plan. 

Maybe we can use the khttps://github.com/LSSTDESC/descwl-shear-sims package to act as our reference  implementation for the forward model in stage 0, and stage 0 is adding the code to implement a/several forward model that we will use for inference, validated against that package.

**Comment by ismael-mendoza** [comment]
> Maybe we can use the https://github.com/LSSTDESC/descwl-shear-sims package to act as our reference implementation for the forward model in stage 0

Thanks @EiffL for the suggestion. To make sure I understand - are you suggesting that for stage 0 we use the functions in `descwl-shear-sims` directly? Or we extract the relevant pieces of code from there (perhaps modified for our needs)? 

> stage 0 is adding the code to implement a/several forward model that we will use for inference, validated against that package.

What exactly will be validate here ? Our inference methods of shear or the forward model ?

**Comment by ismael-mendoza** [comment]
I also assigned some other pixel-level people in the group to this issue. @rearmstr @mdschneider @aguinot @aboucaud  feel free to chime in too :)

**Comment by EiffL** [comment]
yeah, my point is that the `descwl-shear-sims` is already built around GalSim to emulate the DM images. And it can go from simple images, to all sorts of complex artifacts:
https://github.com/LSSTDESC/descwl-shear-sims/blob/master/tutorials/tutorial-basic.md#simple-simulation

**Comment by EiffL** [comment]
so we can use that as a reference forward model (instead of `For now, use galsim` in our current plan). We can probably adapt code from that repo at a later stage also.

But yeah, then we implement a matching forward model that would be able to reproduce the same images, and be used in our inference frameworks.

**Comment by ismael-mendoza** [comment]
That sounds good to me, so for stage 0 we use `desc-shear-sims` directly for our simulations and as our forward model. We can already try to put together our inference procedures and run them on these sims (we perhaps just choose the flags to not have too many complex artifacts for now).

In later stages we can implement our own forward model that matches this code and do inference on that.

**Comment by EiffL** [comment]
yeah I mean, my thinking was in stage 0 to have the ref. model provided by shear-sims, but we need a separate forwrad model with which to do the inference. Could be from bliss, jif, etc...

**Comment by ismael-mendoza** [comment]
oh ok, yeah that makes sense now. We still need to build our own forward model whose images can be designed to match the ones in shear-sims

**Comment by ismael-mendoza** [comment]
This list is a bit big and overwhelming. I am closing this in favor of a more focused to-do list for stage0 which I'm about to open. In the future, we can refer back to this list once stage 0 is completed.
